CREATE TABLE plant
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    common_name        VARCHAR(255),
    image              VARCHAR(255),
    sowing             VARCHAR(255),
    row_spacing        VARCHAR(255),
    minimum_root_depth VARCHAR(255),
    days_to_harvest    VARCHAR(255),
    light              INTEGER,
    growth_rate        VARCHAR(255),
    CONSTRAINT pk_plant PRIMARY KEY (id)
);