spring:
  application:
    name: plantr

  datasource:
    url: jdbc:postgresql://localhost:5436/plantr
    driver-class-name: org.postgresql.Driver
    username: plantradmin
    password: plantradmin
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8080