version: "3.8"
services:
  postgres-db:
    container_name: plantr
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: plantradmin
      POSTGRES_PASSWORD: plantradmin
      POSTGRES_DB: plantr
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5436:5432"

volumes:
  postgresql_data:
    driver: local